base_url = "https://webring.domain.tld"
ring_name = "Webring"
ring_description = "A webring to connect member sites."
ring_owner = "Webring Organization / Person"
ring_owner_site = "https://domain.tld"

filepath_list = "./websites.json"
path_output = "./webring"
path_assets = "./data/assets"
path_templates = "./data/templates"

shuffle = false
verbose = false
skip_minify = false